CREATE TABLE [den].[AltarMats] (
	[Facility] NVARCHAR(50) NOT NULL
	,[T1Mat] NVARCHAR(50) NOT NULL
	,[T2Mat] NVARCHAR(50) NOT NULL
	,[T3Mat] NVARCHAR(50) NOT NULL
	,[T4Mat] NVARCHAR(50) NOT NULL
	,CONSTRAINT [PK_AltarMats] PRIMARY KEY ([Facility])
	)
