// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DragaliaApi.Models
{
    public partial class Ability
    {
        public Ability()
        {
            Passives = new HashSet<Passive>();
            WyrmprintAbilities = new HashSet<WyrmprintAbility>();
        }

        public int AbilityId { get; set; }
        public string Ability1 { get; set; }
        public string GenericName { get; set; }
        public int AbilityGroupId { get; set; }

        public virtual AbilityGroup AbilityGroup { get; set; }
        public virtual ICollection<Passive> Passives { get; set; }
        public virtual ICollection<WyrmprintAbility> WyrmprintAbilities { get; set; }
    }
}