// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DragaliaApi.Models
{
    public partial class AbilityGroup
    {
        public AbilityGroup()
        {
            Abilities = new HashSet<Ability>();
        }

        public int AbilityGroupId { get; set; }
        public string AbilityGroup1 { get; set; }

        public virtual ICollection<Ability> Abilities { get; set; }
    }
}