// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DragaliaApi.Models
{
    public partial class AccountFacility
    {
        public int AccountId { get; set; }
        public int FacilityId { get; set; }
        public int CopyNumber { get; set; }
        public int CurrentLevel { get; set; }
        public int WantedLevel { get; set; }

        public virtual Account Account { get; set; }
        public virtual Facility Facility { get; set; }
    }
}