// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DragaliaApi.Models
{
    public partial class Account
    {
        public Account()
        {
            AccountAdventurers = new HashSet<AccountAdventurer>();
            AccountDragons = new HashSet<AccountDragon>();
            AccountFacilities = new HashSet<AccountFacility>();
            AccountInventories = new HashSet<AccountInventory>();
            AccountPassives = new HashSet<AccountPassive>();
            AccountWeapons = new HashSet<AccountWeapon>();
            AccountWyrmprints = new HashSet<AccountWyrmprint>();
        }

        public int AccountId { get; set; }
        public string AccountName { get; set; }
        public string AccountEmail { get; set; }
        public string AuthId { get; set; }
        public bool? Active { get; set; }

        public virtual ICollection<AccountAdventurer> AccountAdventurers { get; set; }
        public virtual ICollection<AccountDragon> AccountDragons { get; set; }
        public virtual ICollection<AccountFacility> AccountFacilities { get; set; }
        public virtual ICollection<AccountInventory> AccountInventories { get; set; }
        public virtual ICollection<AccountPassive> AccountPassives { get; set; }
        public virtual ICollection<AccountWeapon> AccountWeapons { get; set; }
        public virtual ICollection<AccountWyrmprint> AccountWyrmprints { get; set; }
    }
}