// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DragaliaApi.Models
{
    public partial class AccountDragon
    {
        public int AccountId { get; set; }
        public int DragonId { get; set; }
        public int Unbind { get; set; }
        public int UnbindWanted { get; set; }

        public virtual Account Account { get; set; }
        public virtual Dragon Dragon { get; set; }
    }
}