// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DragaliaApi.Models
{
    public partial class Dragon
    {
        public Dragon()
        {
            AccountDragons = new HashSet<AccountDragon>();
            DragonEssences = new HashSet<DragonEssence>();
        }

        public int DragonId { get; set; }
        public string Dragon1 { get; set; }
        public int Rarity { get; set; }
        public int ElementId { get; set; }
        public bool? Active { get; set; }

        public virtual Element Element { get; set; }
        public virtual ICollection<AccountDragon> AccountDragons { get; set; }
        public virtual ICollection<DragonEssence> DragonEssences { get; set; }
    }
}