// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DragaliaApi.Models
{
    public partial class Element
    {
        public Element()
        {
            Passives = new HashSet<Passive>();
            Weapons = new HashSet<Weapon>();
        }

        public int ElementId { get; set; }
        public string Element1 { get; set; }
        public int SortOrder { get; set; }
        public bool? Active { get; set; }

        public virtual ICollection<Passive> Passives { get; set; }
        public virtual ICollection<Weapon> Weapons { get; set; }
    }
}