// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DragaliaApi.Models
{
    public partial class Passive
    {
        public Passive()
        {
            AccountPassives = new HashSet<AccountPassive>();
            PassiveCraftings = new HashSet<PassiveCrafting>();
        }

        public int PassiveId { get; set; }
        public int WeaponTypeId { get; set; }
        public int ElementId { get; set; }
        public int AbilityId { get; set; }
        public int AbilityNumber { get; set; }
        public int SortOrder { get; set; }
        public bool? Active { get; set; }

        public virtual Ability Ability { get; set; }
        public virtual Element Element { get; set; }
        public virtual WeaponType WeaponType { get; set; }
        public virtual ICollection<AccountPassive> AccountPassives { get; set; }
        public virtual ICollection<PassiveCrafting> PassiveCraftings { get; set; }
    }
}