// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DragaliaApi.Models
{
    public partial class UpgradeType
    {
        public UpgradeType()
        {
            WeaponUpgrades = new HashSet<WeaponUpgrade>();
            WyrmprintUpgrades = new HashSet<WyrmprintUpgrade>();
        }

        public int UpgradeTypeId { get; set; }
        public string UpgradeType1 { get; set; }
        public bool? Active { get; set; }

        public virtual ICollection<WeaponUpgrade> WeaponUpgrades { get; set; }
        public virtual ICollection<WyrmprintUpgrade> WyrmprintUpgrades { get; set; }
    }
}