// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DragaliaApi.Models
{
    public partial class WeaponUnbindLimit
    {
        public int WeaponRarity { get; set; }
        public int RefinementLevel { get; set; }
        public int MaxUnbindLevel { get; set; }
    }
}