// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DragaliaApi.Models
{
    public partial class WeaponSeries
    {
        public WeaponSeries()
        {
            Weapons = new HashSet<Weapon>();
        }

        public int WeaponSeriesId { get; set; }
        public string WeaponSeries1 { get; set; }
        public int SortOrder { get; set; }
        public bool? Active { get; set; }

        public virtual ICollection<Weapon> Weapons { get; set; }
    }
}