// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DragaliaApi.Models
{
    public partial class WyrmprintLevelLimit
    {
        public int WyrmprintRarity { get; set; }
        public int UnbindLevel { get; set; }
        public int MaxWyrmprintLevel { get; set; }
    }
}