// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DragaliaApi.Models
{
    public partial class WyrmprintAbility
    {
        public int WyrmprintId { get; set; }
        public int AbilityId { get; set; }
        public int AbilitySlot { get; set; }
        public int AbilityLevel { get; set; }

        public virtual Ability Ability { get; set; }
        public virtual Wyrmprint Wyrmprint { get; set; }
    }
}